project Kon Khay Hoi/KonKhayHoi/KonKhayHoi/Models/Farm.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonKhayHoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Farm()
        {
            this.Circulations = new HashSet<Circulation>();
        }
    
        public int FID { get; set; }
        public string F_name { get; set; }
        public string F_tel { get; set; }
        public string dateStart { get; set; }
        public string MonthOfSale { get; set; }
        public string F_no { get; set; }
        public string F_subD { get; set; }
        public string F_sub { get; set; }
        public string F_ProV { get; set; }
        public Nullable<int> Invest { get; set; }
        public string AID { get; set; }
    
        public virtual admin admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Circulation> Circulations { get; set; }
    }
}

project Kon Khay Hoi/KonKhayHoi/KonKhayHoi/Controllers/farmController.cs
using KonKhayHoi.Models;
using System;
using System.Linq;
using System.Web.Mvc;



namespace KonKhayHoi.Controllers
{
    public class farmController : Controller
    {
        private KonKhayHoiEntities db = new KonKhayHoiEntities();

        // GET: farm
        public ActionResult changPassword()
        {
            return View();
        }


        public ActionResult dataFarm()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult dataFarm(admin pro)
        {


            Farm farm= new Farm ();

            

            farm.Invest = 1;
            farm.F_name = Request.Form["name"];
            farm.F_tel = Request.Form["tel"];
            farm.dateStart = Request.Form["dateStart"];
            farm.MonthOfSale = Request.Form["MonthOfSale"];
            farm.F_no = Request.Form["no"];
            farm.F_subD = Request.Form["subD"];
            farm.F_sub = Request.Form["sub"];
            farm.F_ProV = Request.Form["proV"];
            farm.AID = "A0001";

            if (ModelState.IsValid)
            {
                db.Farms.Add(farm);
                db.SaveChanges();
                ViewBag.Message = "บันทึกสำเร็จ";
            }

            return View();
         }


        public ActionResult addRevenue()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult addRevenue(int weight,int amount)
        {
            Revenue revenue = new Revenue();


            revenue.Weight = weight;
            revenue.amount = amount;
            revenue.R_list = Request.Form["date"];
            revenue.R_list = Request.Form["list"];
            revenue.Shop = Request.Form["shop"];
            revenue.payee = Request.Form["payee"];
            


            if (ModelState.IsValid)
            {
                db.Revenues.Add(revenue);
                db.SaveChanges();
                ViewBag.Message = "บันทึกสำเร็จ";
                

            }
            
            return View();

        }

        public ActionResult addFarm()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult addFarm( int investment)
        {
            admin addfarm = new admin();

            addfarm.AID = "A0001";
            addfarm.A_Investment = investment;
            addfarm.A_name = Request.Form["name"];
            addfarm.A_lastname = Request.Form["lastname"];
            addfarm.A_no = Request.Form["no"];
            addfarm.A_subD = Request.Form["subD"];
            addfarm.A_sub = Request.Form["sub"];
            addfarm.A_ProV = Request.Form["proV"];
            addfarm.A_tel = Request.Form["tel"];
            addfarm.A_pass = Request.Form["pass"];

            if (ModelState.IsValid)
            {
                db.admins.Add(addfarm);
                db.SaveChanges();
                ViewBag.Message = "สมัครสมาชิกสำเร็จ";


            }
            return View();
        }

        public ActionResult addExpenditure()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult addExpenditure(int amount)
        {
            Expenditure expenditure = new Expenditure();


            expenditure.amount = amount;
         
            expenditure.E_list = Request.Form["date"];
            expenditure.E_list = Request.Form["list"];
            expenditure.payor = Request.Form["payor"];
            expenditure.note = Request.Form["note"];
            expenditure.CID = 1;


            if (ModelState.IsValid)
            {
                db.Expenditures.Add(expenditure);
                db.SaveChanges();
                ViewBag.Message = "บันทึกสำเร็จ";


            }

            return View();

        }



        public ActionResult viewExpenditure()
        {
            Expenditure listiview = new Expenditure();
               
            return View(listiview.ToString());
        }

    }
}

project Kon Khay Hoi/KonKhayHoi/KonKhayHoi/Views/farm/ChangPassword.cshtml
<!DOCTYPE HTML>
<html lang="en">
<head>

    <title>Kon Khay Hoi</title>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/x-icon" href="~/bootstrap/style/images/konKhayHoi.png">
    <link rel="stylesheet" type="text/css" href="~/bootstrap/style/css/style.css" media="all">
    <link href='http://fonts.googleapis.com/css?family=Amaranth' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
    
    <script src="~/bootstrap/style/js/jquery-1.6.4.min.js"></script>
    <script src="~/bootstrap/style/js/ddsmoothmenu.js"></script>
    <script src="~/bootstrap/style/js/jquery.jcarousel.js"></script>
    <script src="~/bootstrap/style/js/jquery.prettyPhoto.js"></script>
    <script src="~/bootstrap/style/js/carousel.js"></script>
    <script src="~/bootstrap/style/js/jquery.flexslider-min.js"></script>
    <script src="~/bootstrap/style/js/jquery.masonry.min.js"></script>
    <script src="~/bootstrap/style/js/jquery.slickforms.js"></script>
</head>

@using (Html.BeginForm())
{
    <body>
        <div id="wrapper">
            @Html.AntiForgeryToken()
            <div id="sidebar">
                <div id="logo"><center><img src="~/bootstrap/style/images/logo.png"></center></div>
                <div id="menu" class="menu-v">
                    <ul>
                        <li><a href="datafarm.html" class="active">ข้อมูลฟาร์ม</a></li>
                        <li><a href="profile.html" class="active">แก้ไขข้อมูลส่วนตัว</a></li>
                        <li><a href="viewRevenue.html" class="active">รายได้</a></li>
                        <li><a href="viewExpenditure.html" class="active">รายจ่าย</a></li>
                        <li><a href="CheckProfit.html" class="active">ตรวจสอบกำไร</a></li>
                        <li><a href="Circulation.html" class="active">ตรวจสอบยอดขาย</a></li>
                        <li><a href="ViewPN.html" class="active">เพิ่ม แก้ไข(หุ้นส่วน)</a></li>
                        <li><a href="Viewstore.html" class="active">ดูข้อมูลร้านรับซื้อ</a></li>
                        <li onclick="location.href='@Url.Action("ChangPassword", "Admin")';">เปลี่ยนรหัสผ่าน</li>
                        <li><a href="#" class="active">ออกจากระบบ</a></li>
                    </ul>
                </div>
            </div>

            <div id="content">
                <font color="#fffff">  <h5 class="title">สวัสดี คุณหอยแครง ทะเลไทย</h5> </font>
                <div class="line"></div>
                <div class="container-fluid">

                    <div class="animated fadeIn">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-header">
                                        <strong><img src="~/bootstrap/style/images/pass.png"></strong>
                                    </div>
                                    <div class="card-block">
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <div class="form-group">
                                                    <label for="name">รหัสผ่านเก่า</label>
                                                    <input type="password" class="form-control" id="namefarm" placeholder="">
                                                </div>
                                            </div>
                                        </div>
                                        <!--/.row-->
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <div class="form-group">
                                                    <label for="ccnumber">รหัสผ่านใหม่</label>
                                                    <input type="password" class="form-control" id="tel" placeholder="">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">

                                            <div class="col-sm-12">
                                                <div class="form-group">
                                                    <label for="ccnumber">ยืนยันรหัสผ่านใหม่</label>
                                                    <input type="password" class="form-control" id="ccnumber" placeholder="">
                                                </div>
                                                <br>
                                                <div class="form-group form-actions">
                                                    <center>
                                                        <button type="submit" class="btn btn-success btn-lg">&nbsp;&nbsp;&nbsp;บันทึก&nbsp;&nbsp;&nbsp;</button>&nbsp;&nbsp;
                                                </center>
                                                        </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
                <div class="clear"></div>
                <script src="~/bootstrap/style/js/scripts.js"></script>
                <!--[if !IE]> -->
                <script src="~/bootstrap/style/js/jquery.corner.js"></script>
    </body>
}
</html>

project Kon Khay Hoi/KonKhayHoi/KonKhayHoi/Views/farm/addExpenditure.cshtml
<!DOCTYPE HTML>
<html lang="en">
<head>
    <title>Kon Khay Hoi</title>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/x-icon" href="~/bootstrap/style/images/konKhayHoi.png">
    <link rel="stylesheet" type="text/css" href="~/bootstrap/style/css/style.css" media="all">
    <link href='http://fonts.googleapis.com/css?family=Amaranth' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,400italic,700,700italic' rel='stylesheet' type='text/css'>

    <script src="~/bootstrap/style/js/jquery-1.6.4.min.js"></script>
    <script src="~/bootstrap/style/js/ddsmoothmenu.js"></script>
    <script src="~/bootstrap/style/js/jquery.jcarousel.js"></script>
    <script src="~/bootstrap/style/js/jquery.prettyPhoto.js"></script>
    <script src="~/bootstrap/style/js/carousel.js"></script>
    <script src="~/bootstrap/style/js/jquery.flexslider-min.js"></script>
    <script src="~/bootstrap/style/js/jquery.masonry.min.js"></script>
    <script src="~/bootstrap/style/js/jquery.slickforms.js"></script>
</head>
@using (Html.BeginForm())
{
    <body>
        <div id="wrapper">
            @Html.AntiForgeryToken()
            <div id="sidebar">
                <div id="logo"><center><img src="~/bootstrap/style/images/logo.png"></center></div>
                <div id="menu" class="menu-v">
                    <ul>
                        <li><a href="datafarm.html" class="active">ข้อมูลฟาร์ม</a></li>
                        <li><a href="profile.html" class="active">แก้ไขข้อมูลส่วนตัว</a></li>
                        <li><a href="viewRevenue.html" class="active">รายได้</a></li>
                        <li><a href="viewExpenditure.html" class="active">รายจ่าย</a></li>
                        <li><a href="CheckProfit.html" class="active">ตรวจสอบกำไร</a></li>
                        <li><a href="Circulation.html" class="active">ตรวจสอบยอดขาย</a></li>
                        <li><a href="ViewPN.html" class="active">เพิ่ม แก้ไข(หุ้นส่วน)</a></li>
                        <li><a href="Viewstore.html" class="active">ดูข้อมูลร้านรับซื้อ</a></li>
                        <li><a href="changPassword.html" class="active">เปลี่ยนรหัสผ่าน</a></li>
                        <li><a href="#" class="active">ออกจากระบบ</a></li>
                    </ul>
                </div>
            </div>

            <div id="content">
                <font color="#fffff">  <h5 class="title">สวัสดี คุณหอยแครง ทะเลไทย</h5> </font>
                <div class="line"></div>
                <div class="container-fluid">
                    <table border="0" background="style/images/bgt.png">
                        <tr>
                            <td align="center"> <a href="viewExpenditure.html"><img src="~/bootstrap/style/images/viewE.png"> </td>
                            <td td align="center" bgcolor="#ffffff"> <a href="addExpenditure.html"> <img src="~/bootstrap/style/images/addE.png">  </td>
                        </tr>
                    </table>
                    <div class="animated fadeIn">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card">
                                    <div style="width:100%; height:450px; overflow-y: scroll; scrollbar-arrow-color:blue; scrollbar-face-color: #e7e7e7; scrollbar-3dlight-color: #a0a0a0; scrollbar-darkshadow-color:#888888">
                                        <div class="card-block">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <font size="5" color="green">@ViewBag.Message</font><br>
                                                    <div class="form-group">
                                                        <label for="name">รายการ</label>
                                                        <input type="text" class="form-control" name="list" required="required" id="namefarm" placeholder="">
                                                    </div>
                                                </div>
                                            </div>
                                            <!--/.row-->
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        <label for="ccnumber">จำนวนเงิน</label>
                                                        <input type="text" class="form-control" name="amount" id="tel" required="required" placeholder="">
                                                    </div>
                                                </div>
                                            </div>
                                            <!--/.row-->
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        
                                                        <label for="ccnumber">ผู้จ่ายเงิน</label>
                                                        <input type="text" class="form-control" name="payor" required="required" id="ccnumber" placeholder="">
                                                    </div>
                                                </div>
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        <label for="ccnumber">วันที่จ่าย</label>
                                                        <input type="text" class="form-control" name="date" id="ccnumber" required="required" placeholder="ปี-เดือน-วัน เช่น 2560-01-01">
                                                    </div>
                                                </div>
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        <label for="ccnumber">หมายเหตุ</label>
                                                        <input type="text" class="form-control" name="note" id="ccnumber" placeholder="">
                                                    </div>
                                                    <br>
                                                    <div class="form-group form-actions">
                                                        <center>
                                                            <input class="btn btn-success btn-lg" type="submit" value="บันทึก" />
                                                            
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
                <script src="~/bootstrap/style/js/scripts.js"></script>
                <!--[if !IE]> -->
                <script src="~/bootstrap/style/js/jquery.corner.js"></script>
    </body>
}
</html>

project Kon Khay Hoi/KonKhayHoi/KonKhayHoi/Views/farm/dataFarm.cshtml
<!DOCTYPE HTML>
<html lang="en">
<head>

    <title>Kon Khay Hoi</title>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/x-icon" href="~/bootstrap/style/images/konKhayHoi.png">
    <link rel="stylesheet" type="text/css" href="~/bootstrap/style/css/style.css" media="all">
    <link href='http://fonts.googleapis.com/css?family=Amaranth' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
    
    <script src="~/bootstrap/style/js/jquery-1.6.4.min.js"></script>
    <script src="~/bootstrap/style/js/ddsmoothmenu.js"></script>
    <script src="~/bootstrap/style/js/jquery.jcarousel.js"></script>
    <script src="~/bootstrap/style/js/jquery.prettyPhoto.js"></script>
    <script src="~/bootstrap/style/js/carousel.js"></script>
    <script src="~/bootstrap/style/js/jquery.flexslider-min.js"></script>
    <script src="~/bootstrap/style/js/jquery.masonry.min.js"></script>
    <script src="~/bootstrap/style/js/jquery.slickforms.js"></script>
</head>

@using (Html.BeginForm())
{
    <body>
        <div id="wrapper">
            @Html.AntiForgeryToken()
            <div id="sidebar">
                <div id="logo"><center><img src="~/bootstrap/style/images/logo.png"></center></div>
                <div id="menu" class="menu-v">
                    <ul>
                        <li><a class="active" onclick="location.href='@Url.Action("dataFarm", "farm")';">ข้อมูลฟาร์ม</a></li>
                        <li><a class="active" onclick="location.href='@Url.Action("profile", "Admin")';">แก้ไขข้อมูลส่วนตัว</a></li>
                        <li><a href="viewRevenue.html" class="active">รายได้</a></li>
                        <li><a href="viewExpenditure.html" class="active">รายจ่าย</a></li>
                        <li><a href="CheckProfit.html" class="active">ตรวจสอบกำไร</a></li>
                        <li><a href="Circulation.html" class="active">ตรวจสอบยอดขาย</a></li>
                        <li><a href="ViewPN.html" class="active">เพิ่ม แก้ไข(หุ้นส่วน)</a></li>
                        <li><a href="Viewstore.html" class="active">ดูข้อมูลร้านรับซื้อ</a></li>
                        <li onclick="location.href='@Url.Action("ChangPassword", "Admin")';">เปลี่ยนรหัสผ่าน</li>
                        <li><a href="#" class="active">ออกจากระบบ</a></li>
                    </ul>
                </div>
            </div>

            <div id="content">
                <font color="#fffff">  <h5 class="title">สวัสดี คุณหอยแครง ทะเลไทย</h5> </font>
                <div class="line"></div>
                <div class="container-fluid">

                    <div class="animated fadeIn">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-header">
                                        <strong><img src="~/bootstrap/style/images/datafarm.png"></strong>
                                    </div>
                                    <div style="width:100%; height:500px; overflow-y: scroll; scrollbar-arrow-color:blue; scrollbar-face-color: #e7e7e7; scrollbar-3dlight-color: #a0a0a0; scrollbar-darkshadow-color:#888888">
                                        <div class="card-block">
                                            <div class="row">
                                                <font size="5" color="green">@ViewBag.Message</font><br>
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        <label for="name">ชื่อผู้ใช้งาน</label>
                                                        <input type="text" class="form-control" name="username"  id="namefarm" placeholder="">
                                                    </div>
                                                </div>
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        <label for="name">รหัสผ่าน</label>
                                                        <input type="text" class="form-control" name="pass"  id="namefarm" placeholder="">
                                                    </div>
                                                </div>
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        <label for="name">ชื่อฟาร์ม</label>
                                                        <input type="text" class="form-control" name="name" value="@HttpContext.Current.Session["DFname"]" id="namefarm" placeholder="">
                                                    </div>
                                                </div>
                                            </div>
                                            <!--/.row-->
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        <label for="ccnumber">เบอร์โทร</label>
                                                        <input type="text" class="form-control" name="tel" value="@HttpContext.Current.Session["DFtel"]" id="tel" placeholder="">

                                                    </div>
                                                </div>
                                            </div>
                                            <input type="hidden" name="" />
                                            <!--/.row-->
                                            <div class="row">
                                                <div class="col-sm-4">
                                                    <div class="form-group">
                                                        <label for="cvv">บ้านเลขที่</label>
                                                        <input type="text" class="form-control" name="no" value="@HttpContext.Current.Session["DFno"]" id="no_" placeholder="">
                                                    </div>
                                                </div>
                                                <div class="col-sm-4">
                                                    <div class="form-group">
                                                        <label for="cvv">ตำบล</label>
                                                        <input type="text" class="form-control" name="subD" value="@HttpContext.Current.Session["DFsubD"]" id="sub_d" placeholder="">
                                                    </div>
                                                </div>
                                            </div>
                                            <!--/.row-->
                                            <div class="row">
                                                <div class="col-sm-4">
                                                    <div class="form-group">
                                                        <label for="cvv">อำเภอ</label>
                                                        <input type="text" class="form-control" name="sub" value="@HttpContext.Current.Session["DFsub"]" id="cvv" placeholder="">
                                                    </div>
                                                </div>
                                                <div class="col-sm-4">
                                                    <div class="form-group">
                                                        <label for="cvv">จังหวัด</label>
                                                        <input type="text" class="form-control" name="proV" value="@HttpContext.Current.Session["DFproV"]" id="cvv" placeholder="">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        <label for="ccnumber">วันที่เริ่มลงทุน</label>
                                                        <input type="text" class="form-control" name="dateStart" value="@HttpContext.Current.Session["DFdateStart"]" id="ccnumber" placeholder="เช่น 01/01/2560">
                                                    </div>
                                                </div>
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        <label for="ccnumber">เดือน ปีที่คิดว่าจะขายได้</label>
                                                        <input type="text" class="form-control" name="MonthOfSale" value="@HttpContext.Current.Session["DFMonthOfSale"]" id="ccnumber" placeholder="เช่น 01/2560">
                                                    </div>
                                                    <br>
                                                    <div class="form-group form-actions">
                                                        <center>
                                                            <button type="submit" class="btn btn-success btn-lg">&nbsp;&nbsp;&nbsp;บันทึก&nbsp;&nbsp;&nbsp;</button>&nbsp;&nbsp;
                                                            <button type="submit" class="btn btn-danger btn-lg">เริ่มรอบใหม่</button>
                                                        </center>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
                <script src="~/bootstrap/style/js/scripts.js"></script>
                <!--[if !IE]> -->
                <script src="~/bootstrap/style/js/jquery.corner.js"></script>
    </body>
}
</html>