project Kon Khay Hoi/KonKhayHoi/KonKhayHoi/Controllers/loginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KonKhayHoi.Models;
using System.Data.Entity.Validation;

namespace KonKhayHoi.Controllers
{

    public class loginController : Controller
    {
        KonKhayHoiEntities db = new KonKhayHoiEntities();
        // GET: login


        public ActionResult login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult login(admin Pro)
        {
            string username = Request.Form["username"];
            string password = Request.Form["password"];

            if (ModelState.IsValid)
            {
                var checkA = db.admins.Where(a => a.AID.Equals(username) && a.A_pass.Equals(password)).FirstOrDefault();
                var checkP = db.Partners.Where(a => a.PID.Equals(username) && a.P_pass.Equals(password)).FirstOrDefault();
                var checkS = db.Shops.Where(a => a.SID.Equals(username) && a.S_pass.Equals(password)).FirstOrDefault();
                if (checkA != null)
                {
                    var cookie_AID = new HttpCookie("AID");
                    cookie_AID.Value = checkA.AID;
                    Response.Cookies.Add(cookie_AID);

                    return RedirectToAction("dataFarm", "farm");
                }
                else if (checkP != null)
                {
                    var cookie_PID = new HttpCookie("PID");
                    cookie_PID.Value = checkP.PID;
                    Response.Cookies.Add(cookie_PID);

                    return RedirectToAction("PNcheckProfit", "partner");
                }
                else if (checkS != null)
                {
                    var cookie_SID = new HttpCookie("SID");
                    cookie_SID.Value = checkS.SID;
                    Response.Cookies.Add(cookie_SID);

                    return RedirectToAction("STdatastore", "shop");
                }
                else
                {
                    ViewBag.Message = "ª×èÍ¼Ùéãªé ËÃ×ÍÃËÑÊ¼èÒ¹¼Ô´";
                }


            }

            return View();
        }

    }




}

project Kon Khay Hoi/KonKhayHoi/KonKhayHoi/Views/index/Index.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <title>Kon Khay Hoi</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
    <link rel="stylesheet" href="~/bootstrap/assets/css/main.css" />
    <!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
    <!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
</head>
<body class="landing">

    <!-- Page Wrapper -->
    <div id="page-wrapper">

        <!-- Header -->
        <header id="header" class="alt">

            <nav id="nav">
                <ul>
                    <li class="special">
                       @Html.ActionLink("เข้าสู่ระบบ/สมัครสมาชิก","login","login")
                    </li>
                </ul>
            </nav>
        </header>

        <!-- Banner -->
        <section id="banner">
            <div class="inner">
                <h2>คน ขาย หอย</h2>
                <p>
                    เว็บการจัดการฟาร์มหอย<br />
                    และพบปะร้านรับซื้อ<br /><br>
                    <img src="~/bootstrap/style/images/hoi.png">
                </p>
            </div>
        </section>
    </div>

    <!-- Scripts -->
    <script src="~/bootstrap/assets/js/jquery.min.js"></script>
    <script src="~/bootstrap/assets/js/jquery.scrollex.min.js"></script>
    <script src="~/bootstrap/assets/js/jquery.scrolly.min.js"></script>
    <script src="~/bootstrap/assets/js/skel.min.js"></script>
    <script src="~/bootstrap/assets/js/util.js"></script>
    <!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
    <script src="~/bootstrap/assets/js/main.js"></script>

</body>
</html>