project Kon Khay Hoi/KonKhayHoi/KonKhayHoi/Models/Shop.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonKhayHoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public string SID { get; set; }
        public string Name { get; set; }
        public string S_name { get; set; }
        public string S_lastname { get; set; }
        public string S_tel { get; set; }
        public Nullable<int> purchasedAmount { get; set; }
        public string S_pass { get; set; }
        public string S_no { get; set; }
        public string S_subD { get; set; }
        public string S_sub { get; set; }
        public string S_ProV { get; set; }
        public Nullable<int> state { get; set; }
    }
}

project Kon Khay Hoi/KonKhayHoi/KonKhayHoi/Controllers/shopController.cs
using KonKhayHoi.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace KonKhayHoi.Controllers
{
    public class shopController : Controller
    {
        private KonKhayHoiEntities db = new KonKhayHoiEntities();

        // ดูข้อมูลร้ารรับซื้อ 
        public ActionResult STdatastore()
        {

            if (ModelState.IsValid)
            {
                var checkW = db.Shops.FirstOrDefault();
                if (checkW != null)
                {
                    Session["Suser"] = checkW.SID;

                    Session["Sname"] = checkW.S_name;

                    Session["Slast"] = checkW.S_lastname;

                    Session["Stel"] = checkW.S_tel;

                    Session["Sno"] = checkW.S_no;

                    Session["SsubD"] = checkW.S_subD;

                    Session["Ssub"] = checkW.S_sub;

                    Session["SproV"] = checkW.S_ProV;

                    Session["SpurchasedAmount"] = checkW.purchasedAmount;
                    Session["Sstate"] = checkW.state;


                }

            }

            return View();
        }



        //ดูข้อมูลฟาร์ม
        public ActionResult STselectdatafarm()
        {
            string query2 = "SELECT * FROM Farm ";
            var test = db.Database.SqlQuery<Farm>(query2).ToList();
            return View(Tuple.Create(test));

        }


        //ดูร้านรับซื้อ
        public ActionResult Viewstore()
        {
            string query2 = "SELECT * FROM Shop ";
            var test = db.Database.SqlQuery<Shop>(query2).ToList();
            return View(Tuple.Create(test));

        }

        //แก้ไขข้อมูลร้าน
        public ActionResult STchangdatastore()

        {
            Shop shop = new Shop();

            string SID_update = Request.Form["username_update"];
            string Name_update = Request.Form["Name_update"];
            string S_name_update = Request.Form["names_update"];
            string S_lastname_update = Request.Form["lastname_update"];
            string S_tel_update = Request.Form["tel_update"];
            string purchasedAmount_update = Request.Form["purchasedAmount_update"];
            string S_no_update = Request.Form["no_update"];
            string S_subD_update = Request.Form["subD_update"];
            string S_sub_update = Request.Form["sub_update"];
            string S_ProV_update = Request.Form["ProV_update"];
            string state_update = Request.Form["state_update"];

            if (ModelState.IsValid)
            {
                if (SID_update != null)
                {

                    var checkUP = db.Shops.Where(a => a.SID.Equals(SID_update)).FirstOrDefault();

                    int A = Convert.ToInt32(purchasedAmount_update);
                    int B = Convert.ToInt32(state_update);

                    checkUP.purchasedAmount = A;
                    checkUP.state = B;
                    checkUP.Name = Name_update;
                    checkUP.S_name = S_name_update;
                    checkUP.S_lastname = S_lastname_update;
                    checkUP.S_tel = S_tel_update;
                    checkUP.S_no = S_no_update;
                    checkUP.S_subD = S_subD_update;
                    checkUP.S_sub = S_sub_update;
                    checkUP.S_ProV = S_ProV_update;



                    db.SaveChanges();

                    Session["Suser"] = checkUP.SID;

                    Session["names"] = checkUP.Name;

                    Session["Sname"] = checkUP.S_name;

                    Session["Slastname"] = checkUP.S_lastname;

                    Session["Stel"] = checkUP.S_tel;

                    Session["Sno"] = checkUP.S_no;

                    Session["SsubD"] = checkUP.S_subD;

                    Session["Ssub"] = checkUP.S_sub;

                    Session["SProV"] = checkUP.S_ProV;

                    Session["SpurchasedAmount"] = checkUP.purchasedAmount;

                    Session["Sstate"] = checkUP.state;

                    return RedirectToAction("STchangdatastore", "Shop");



                }

            }
            return View();
        }


        //เปลี่ยนรหัสผ่าน
        public ActionResult STChangPassword()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult STChangPassword(admin ad)
        {

            string password = Request.Form["password"];
            string newPass = Request.Form["newPass"];
            string cfnewPass = Request.Form["cfnewPass"];
            var CSID = Request.Cookies["SID"].Value;

            var checkeA = db.Shops.Where(a => a.SID.Equals(CSID)).FirstOrDefault();

            if (password != null)
            {
                var check_username = db.Shops.Where(a => a.SID.Equals(CSID)).FirstOrDefault<Shop>();
                if (check_username.S_pass == password)
                {
                    if (newPass == cfnewPass)
                    {
                        check_username.S_pass = newPass;
                        db.SaveChanges();
                        ViewBag.Error1 = "เปลี่ยนรหัสผ่านสำเร็จ";
                        return View();
                    }
                    else
                    {
                        ViewBag.Error1 = "กรอกรหัสผ่านไม่ตรงกัน";
                        return View();
                    }
                }
                else
                {
                    ViewBag.Error2 = "รหัสผ่านผิด";
                    return View();
                }
            }

            return View();
        }



        //สมัครสมาชิกร้านรับซื้อ
        public ActionResult addshop()
        {
            return View();

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult addshop(admin pro)
        {
             Shop shop = new Shop();

            
            shop.SID = "S0005";
            shop.Name = Request.Form["nameS"];
            shop.S_name = Request.Form["name"];
            shop.S_lastname = Request.Form["lastname"];
            shop.S_tel = Request.Form["tel"];
            shop.purchasedAmount = 0;
            shop.S_pass = Request.Form["Pass"];
            shop.S_no = Request.Form["no"];
            shop.S_subD = Request.Form["subD"];
            shop.S_sub = Request.Form["sub"];
            shop.S_ProV = Request.Form["ProV"];
            shop.state = 1;


            if (ModelState.IsValid)
            {
                db.Shops.Add(shop);
                db.SaveChanges();
                ViewBag.Message = "บันทึกสำเร็จ";


            }

            return View();

        }

    }



}

project Kon Khay Hoi/KonKhayHoi/KonKhayHoi/Views/shop/STChangPassword.cshtml
@model Tuple<List<KonKhayHoi.Models.Shop>>
<!DOCTYPE HTML>
<html lang="en">
<head>

    <title>Kon Khay Hoi</title>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/x-icon" href="~/bootstrap/style/images/konKhayHoi.png">
    <link rel="stylesheet" type="text/css" href="~/bootstrap/style/css/style.css" media="all">
    <link href='http://fonts.googleapis.com/css?family=Amaranth' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,400italic,700,700italic' rel='stylesheet' type='text/css'>

    <script src="~/bootstrap/style/js/jquery-1.6.4.min.js"></script>
    <script src="~/bootstrap/style/js/ddsmoothmenu.js"></script>
    <script src="~/bootstrap/style/js/jquery.jcarousel.js"></script>
    <script src="~/bootstrap/style/js/jquery.prettyPhoto.js"></script>
    <script src="~/bootstrap/style/js/carousel.js"></script>
    <script src="~/bootstrap/style/js/jquery.flexslider-min.js"></script>
    <script src="~/bootstrap/style/js/jquery.masonry.min.js"></script>
    <script src="~/bootstrap/style/js/jquery.slickforms.js"></script>
</head>

@using (Html.BeginForm())
{
    <body>
        <div id="wrapper">
            @Html.AntiForgeryToken()
            <div id="sidebar">
                <div id="logo"><center><img src="~/bootstrap/style/images/logo.png"></center></div>
                <div id="menu" class="menu-v">
                    <ul>
                        <li><a href="showList.php" class="active"></a></li>
                        <li><a href="STdatastore.html" class="active">ข้อมูลร้าน</a></li>
                        <li><a class="active" onclick="location.href='@Url.Action("STselectdatafarm", "Shop")';">ข้อมูลฟาร์ม</a></li>
                        <li><a class="active" onclick="location.href='@Url.Action("STchangPassword", "Shop")';">เปลี่ยนรหัสผ่าน</a></li>
                        <li><a href="../main/main.php" class="active">ออกจากระบบ</a></li>
                    </ul>
                </div>
            </div>

            <div id="content">
                <font color="#fffff">  <h5 class="title">สวัสดี คุณหอยแครง ทะเลไทย</h5> </font>
                <div class="line"></div>
                <div class="container-fluid">

                    <div class="animated fadeIn">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-header">
                                        <strong><img src="~/bootstrap/style/images/pass.png"></strong>
                                    </div>
                                    <div class="card-block">
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <div class="form-group">
                                                    <label for="name">รหัสผ่านเก่า</label>
                                                    <input type="password" class="form-control" name="password" id="namefarm" placeholder="">
                                                    @ViewBag.Error
                                                </div>
                                            </div>
                                        </div>
                                        <!--/.row-->
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <div class="form-group">
                                                    <label for="ccnumber">รหัสผ่านใหม่</label>
                                                    <input type="password" class="form-control" name="newPass" id="tel" placeholder="">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">

                                            <div class="col-sm-12">
                                                <div class="form-group">
                                                    <label for="ccnumber">ยืนยันรหัสผ่านใหม่</label>
                                                    <input type="password" class="form-control" name="cfnewPass" id="ccnumber" placeholder="">
                                                    @ViewBag.Error1
                                                </div>
                                                <br>
                                                <div class="form-group form-actions">
                                                    <center>
                                                        <button type="submit" class="btn btn-success btn-lg">&nbsp;&nbsp;&nbsp;บันทึก&nbsp;&nbsp;&nbsp;</button>&nbsp;&nbsp;
                                                    </center>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
            <script src="~/bootstrap/style/js/scripts.js"></script>
            <!--[if !IE]> -->
            <script src="~/bootstrap/style/js/jquery.corner.js"></script>
    </body>
}
</html>

project Kon Khay Hoi/KonKhayHoi/KonKhayHoi/Views/shop/STdatastore.cshtml
@model Tuple<List<KonKhayHoi.Models.Shop>>
<!DOCTYPE HTML>
<html lang="en">
<head>

    <title>Kon Khay Hoi</title>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/x-icon" href="style/images/favicon.png">
    <link rel="stylesheet" type="text/css" href="~/bootstrap/style/css/style.css" media="all">
    <link href='http://fonts.googleapis.com/css?family=Amaranth' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
    <!--[if IE 7]>
    <link rel="stylesheet" type="text/css" href="style/css/ie7.css" media="all">
    <![endif]-->
    <!--[if IE 8]>
    <link rel="stylesheet" type="text/css" href="style/css/ie8.css" media="all">
    <![endif]-->
    <!--[if IE 9]>
    <link rel="stylesheet" type="text/css" href="style/css/ie9.css" media="all">
    <![endif]-->
    <script src="~/bootstrap/style/js/jquery-1.6.4.min.js"></script>
    <script src="~/bootstrap/style/js/ddsmoothmenu.js"></script>
    <script src="~/bootstrap/style/js/jquery.jcarousel.js"></script>
    <script src="~/bootstrap/style/js/jquery.prettyPhoto.js"></script>
    <script src="~/bootstrap/style/js/carousel.js"></script>
    <script src="~/bootstrap/style/js/jquery.flexslider-min.js"></script>
    <script src="~/bootstrap/style/js/jquery.masonry.min.js"></script>
    <script src="~/bootstrap/style/js/jquery.slickforms.js"></script>
</head>
<body>
    <div id="wrapper">
        <div id="sidebar">
            <div id="logo"><center><img src="~/bootstrap/style/images/logo.png"></center></div>
            <div id="menu" class="menu-v">
                <ul>
                    <li><a href="showList.php" class="active"></a></li>
                    <li><a href="STdatastore.html" class="active">ข้อมูลร้าน</a></li>
                    <li><a class="active" onclick="location.href='@Url.Action("STselectdatafarm", "Shop")';">ข้อมูลฟาร์ม</a></li>
                    <li><a class="active" onclick="location.href='@Url.Action("STchangPassword", "Shop")';">เปลี่ยนรหัสผ่าน</a></li>
                    <li><a href="../main/main.php" class="active">ออกจากระบบ</a></li>
                </ul>
            </div>
        </div>

        <div id="content">
            <font color="#fffff">  <h5 class="title">สวัสดี คุณหอยแครง  นะจ๊ะ</h5></font>
            <div class="line"></div>



            <div class="container-fluid">
                <div class="animated fadeIn">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="card">
                                <div class="card-header">
                                    <strong><img src="style/images/datashop.png"></strong>

                                </div>
                                <div style="width: 100%; height: 450px; overflow-y: scroll; scrollbar-arrow-color:blue; scrollbar-face-color: #e7e7e7; scrollbar-3dlight-color: #a0a0a0; scrollbar-darkshadow-color:#888888">
                                    <div class="card-block">
                                        <div class="row">

                                            <div class="col-sm-12">

                                                <div class="form-group">
                                                    <label for="name">ชื่อร้านรับซื้อ</label>
                                                    <input type="text" class="form-control" id="name" name="username" value="@HttpContext.Current.Session["Suser"]" readonly placeholder="">
                                                </div>

                                            </div>

                                        </div>
                                        <!--/.row-->
                                        <div class="row">



                                            <div class="col-sm-4">

                                                <div class="form-group">
                                                    <label for="cvv">ชื่อ</label>
                                                    <input type="text" class="form-control" id="cvv" name="name" value="@HttpContext.Current.Session["Sname"]" readonly placeholder="">
                                                </div>

                                            </div>

                                            <div class="col-sm-4">

                                                <div class="form-group">
                                                    <label for="cvv">นามสกุล</label>
                                                    <input type="text" class="form-control" id="cvv" name="lastname" value="@HttpContext.Current.Session["Slast"]" readonly placeholder="">
                                                </div>

                                            </div>


                                        </div>

                                        <div class="row">

                                            <div class="col-sm-12">

                                                <div class="form-group">
                                                    <label for="ccnumber">เบอร์โทร</label>
                                                    <input type="text" class="form-control" id="ccnumber" name="tel" value="@HttpContext.Current.Session["Stel"]" readonly placeholder="">
                                                </div>

                                            </div>

                                        </div>
                                        <div class="row">

                                            <div class="col-sm-4">

                                                <div class="form-group">
                                                    <label for="cvv">บ้านเลขที่</label>
                                                    <input type="text" class="form-control" id="cvv" name="no" value="@HttpContext.Current.Session["Sno"]" readonly  placeholder="">
                                                </div>

                                            </div>


                                            <div class="col-sm-4">

                                                <div class="form-group">
                                                    <label for="cvv">ตำบล</label>
                                                    <input type="text" class="form-control" id="cvv" name="subD" value="@HttpContext.Current.Session["SsubD"]" readonly  placeholder="">
                                                </div>

                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-sm-4">

                                                <div class="form-group">
                                                    <label for="cvv">อำเภอ</label>
                                                    <input type="text" class="form-control" id="cvv"  name="sub" value="@HttpContext.Current.Session["Ssub"]" readonly placeholder="">
                                                </div>

                                            </div>

                                            <div class="col-sm-4">

                                                <div class="form-group">
                                                    <label for="cvv">จังหวัด</label>
                                                    <input type="text" class="form-control" id="cvv" name="proV" value="@HttpContext.Current.Session["SproV"]" readonly  placeholder="">
                                                </div>

                                            </div>


                                        </div>

                                        <div class="row">

                                            <div class="col-sm-12">

                                                <div class="form-group">
                                                    <label for="ccnumber">จำนวนที่รับซื้อ(ต่อตัน)</label>
                                                    <input type="text" class="form-control" name="purchasedAmount" id="ccnumber" value="@HttpContext.Current.Session["SpurchasedAmount"]" readonly placeholder="เฉพาะตัวเลข">
                                                </div>

                                            </div>

                                            <div class="row">

                                                <div class="col-md-10">
                                                    <label for="ccnumber">สถานะร้าน</label>
                                                    <label class="switch switch-text switch-success">
                                                        <input type="checkbox" class="switch-input" name="state" id="ccnumber" value="@HttpContext.Current.Session["Sstate"]" checked="" readonly placeholder="">
                                                        <span class="switch-label" data-on="On" data-off="Off"></span>
                                                        <span class="switch-handle"></span>
                                                    </label>
                                                    &nbsp;&nbsp;&nbsp;

                                                </div>

                                                <div class="col-sm-12">
                                                    <br>
                                                    <div class="form-group form-actions">
                                                        <center>
                                                            <img src="~/bootstrap/style/images/icon-settings.png" onclick="location.href='@Url.Action("STchangdatastore", "shop")';">
                                                        </center>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
                <script src="~/bootstrap/style/js/scripts.js"></script>
                <!--[if !IE]> -->
                <script src="~/bootstrap/style/js/jquery.corner.js"></script>
                <!-- <![endif]-->
                <!-- <![endif]-->
</body>
</html>

project Kon Khay Hoi/KonKhayHoi/KonKhayHoi/Views/shop/STselectdatafarm.cshtml
@model Tuple<List<KonKhayHoi.Models.Farm>>
<!DOCTYPE HTML>
<html lang="en">
<head>
    <title>Kon Khay Hoi</title>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/x-icon" href="~/bootstrap/style/images/konKhayHoi.png">
    <link rel="stylesheet" type="text/css" href="~/bootstrap/style/css/style.css" media="all">
    <link href='http://fonts.googleapis.com/css?family=Amaranth' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,400italic,700,700italic' rel='stylesheet' type='text/css'>

    <script src="~/bootstrap/style/js/jquery-1.6.4.min.js"></script>
    <script src="~/bootstrap/style/js/ddsmoothmenu.js"></script>
    <script src="~/bootstrap/style/js/jquery.jcarousel.js"></script>
    <script src="~/bootstrap/style/js/jquery.prettyPhoto.js"></script>
    <script src="~/bootstrap/style/js/carousel.js"></script>
    <script src="~/bootstrap/style/js/jquery.flexslider-min.js"></script>
    <script src="~/bootstrap/style/js/jquery.masonry.min.js"></script>
    <script src="~/bootstrap/style/js/jquery.slickforms.js"></script>
</head>
@using (Html.BeginForm())
{
    <body>
        <div id="wrapper">
            @Html.AntiForgeryToken()
            <div id="sidebar">
                <div id="logo"><center><img src="~/bootstrap/style/images/logo.png"></center></div>
                <div id="menu" class="menu-v">
                    <ul>
                        <li><a href="showList.php" class="active"></a></li>
                        <li><a href="STdatastore.html" class="active">ข้อมูลร้าน</a></li>
                        <li><a class="active" onclick="location.href='@Url.Action("STselectdatafarm", "Shop")';">ข้อมูลฟาร์ม</a></li>
                        <li><a class="active" onclick="location.href='@Url.Action("STchangPassword", "Shop")';">เปลี่ยนรหัสผ่าน</a></li>
                        <li><a href="../main/main.php" class="active">ออกจากระบบ</a></li>
                    </ul>
                </div>
            </div>
            

            <div id="content">
                <font color="#fffff">  <h5 class="title">สวัสดี คุณหอยแครง  แต้มเดียว</h5></font>
                <div class="line"></div>



                <div class="animated fadeIn">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="card">
                                <div class="card-header">
                                    <strong><img src="~/bootstrap/style/images/viewE.png"></strong>
                                </div>
                                <div style="width:100%; height:450px; overflow-y: scroll; scrollbar-arrow-color:blue; scrollbar-face-color: #e7e7e7; scrollbar-3dlight-color: #a0a0a0; scrollbar-darkshadow-color:#888888">

                                    <table class=table8_3>
                                        <tr>

                                            <th width=14%><center>ชื่อฟาร์ม</th>
                                            <th width=10%><center>บ้านเลขที่</th>
                                            <th width=10%><center>ตำบล</th>
                                            <th width=15%><center>อำเภอ</th>
                                            <th width=15%><center>จังหวัด</th>
                                            <th width=13%><center>โทร</th>
                                            <th width=15%><center>ช่วงที่ขายได้</th>
                                        </tr>
                                        @foreach (var item in Model.Item1)
                                        {
                                            <tr>
                                                <td>@Html.DisplayFor(modelItem => item.F_name)</td>
                                                <td>@Html.DisplayFor(modelItem => item.F_no  )</td>
                                                <td>@Html.DisplayFor(modelItem => item.F_subD)</td>
                                                <td>@Html.DisplayFor(modelItem => item.F_sub)</td>
                                                <td>@Html.DisplayFor(modelItem => item.F_sub)</td>
                                                <td>@Html.DisplayFor(modelItem => item.F_tel)</td>
                                                <td>@Html.DisplayFor(modelItem => item.MonthOfSale)</td>

                                            </tr>

                                        }
                                    </table>



                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
                <script src="~/bootstrap/style/js/scripts.js"></script>
                <!--[if !IE]> -->
                <script src="~/bootstrap/style/js/jquery.corner.js"></script>
    </body>
}
</html>